### ISSUE TITLE
Assistance with SHARC/LVC Parameterization

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#130]
Dear Sir,

I successfully ran SHARC/LVC (TD-DFT). However, when I came across your paper titled "Highly efficient surface hopping dynamics using a linear vibronic coupling model," I noticed that LVC should be parameterized against a high-level reference instead of using a lower-level method on-the-fly.

I aim to parameterize LVC against MR-CISD theory. However, I am unsure how to prepare the input file for LVC parameterization by MR-CISD computations performed with the COLUMBUS program system using integrals generated with MOLCAS.

Could you please assist me with preparing the file for LVC parameterization and also explain how the COLUMBUS template file should look? I checked the SHARC example directory but could not understand anything. 

Please assist me.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by lukhman9020** [comment]
> Well, it strongly depends on your molecule and the problem you are trying to solve. We have many successful LVC(TDDFT) projects. For metal complexes, most of our work with LVC is parametrized with TDDFT (some exceptions use CAS/RASSCF). MRCISD in COLUMBUS can very quickly become insanely expensive, and for large molecules, it is not even very accurate. If you have a small system, you will get better results parametrizing with (X)MS-CASPT2 or ADC(2). For larger systems, I suggest to stick to TDDFT.

Dear Sir,
My aim is to reproduce similar experimental results. In the experiment, I got around 65 ps time for triplet and singlet populations to become equal, and by SHARC/LVC(TD-DFT), I got around 32 ps for singlet and triplet populations to become equal. That's why I thought to use MRCISD in COLUMBUS a higher theory for LVC parametrization. My system contains 33 atoms with 2 Br atoms. Can (X)MS-CASPT2 or ADC(2) be applied to my system, or will it be computationally more expensive?

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
33 atoms with 2 Br is very very likely impossible with COLUMBUS, because COLUMBUS does not have any RI approximation and is therefore hard-limited to 256 basis functions (and very slow for >150 basis functions). 

ADC(2) for this system size should be doable, but whether ADC(2) is applicable depends on the system. ADC(2) is notoriously bad for metal complexes, but works well for aromatic organic systems (e.g., perylene diimides or other condensed ring systems). ADC(2) is also a single-reference method that will give bad results if you expect S1->S0 decay (or T1->S0).

CASPT2 is only applicable if the required active space is small enough. To judge this, I would need more information on the system (you can also write me on sharc@univie.ac.at if you prefer).

Best,
Sebastian
