### ISSUE TITLE
Assistance Required for Fitting Ensemble Populations 

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#133]
Dear Sir,
When I try to fit ensemble populations using the $SHARC/make_fit.py script, I encounter an error. Initially, I was able to successfully fit the data, but when I tried again, I could not complete the process and received an error. Please help me resolve this issue.
"
The maximum number of function evaluations is exceeded.
Function evaluations 300, initial cost 2.2561e+04, final cost 1.7088e+04, first-order optimality 1.55e+00.
Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/make_fit.py", line 1843, in <module>
    main()
  File "/home/mhgroup1/kumar/sharc/bin/make_fit.py", line 1832, in main
    make_fit(INFOS)
  File "/home/mhgroup1/kumar/sharc/bin/make_fit.py", line 1333, in make_fit
    OPT = spopt.curve_fit(F.call_array, Tdata, Ydata, p0=p0, bounds=bounds, sigma=Yerr, absolute_sigma=Yerr_absol, verbose=2)
  File "/home/mhgroup1/.conda/envs/pysharc_3.0/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py", line 978, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + res.message)
RuntimeError: Optimal parameters not found: The maximum number of function evaluations is exceeded.
" 
Looking forward to hearing from you.
Thank you,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear lukhman9020,
although I did not encounter this error before, it sounds like your fit did not converge. This might be because the data is not prepared appropriately, the kinetic model does not correspond to the data, or the initial guesses for the time constants are not adequate. 

In order to identify the problem and provide further help, I would need to see the fit for myself. You can send the corresponding files (KEYSTROKES.make_fit and the corresponding data file) to sharc@univie.ac.at.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear lukhman9020, although I did not encounter this error before, it sounds like your fit did not converge. This might be because the data is not prepared appropriately, the kinetic model does not correspond to the data, or the initial guesses for the time constants are not adequate.
> 
> In order to identify the problem and provide further help, I would need to see the fit for myself. You can send the corresponding files (KEYSTROKES.make_fit and the corresponding data file) to [sharc@univie.ac.at](mailto:sharc@univie.ac.at).
> 
> Best, Sebastian

OK sir .

**Comment by maisebastian** [comment]
Dear Lukhmanul Hakeem K.,
I repeat here my email reply to you, so that other users can also see what should be done.

Your main problem was that you did not correctly assign the columns from the population files to the kinetic species. Also, the kinetic model was not really appropriate for the data, because there is also non-zero S2 population. Therefore, the fit could not proceed correctly.

Your KEYSTROKES.make_fit file:
```
+ S1 T3 T2 T1                            #Input: [end]
                                         #Input: [end]
+ S1 T3 K13                              #Input: [end]
+ S1 T2 K12                              #Input: [end]
+ S1 T1 K11                              #Input: [end]
                                         #Input: [end]
+ S1                                     #Input: [end]
                                         #Input: [end]
yes                                      #Do you want to use bootstrap data? [False]
                                         #How many bootstrap samples? [100]
/path/to/bootstrap_data/ #Bootstrap data directory: [bootstrap_data/] (autocomplete enabled)
                                         #Do you want to write fitting curves for all bootstrap cycles? [False]
S1 = 2                                   #Input: [end]
T3 = 3                                   #Input: [end]
T2 = 4                                   #Input: [end]
T1 = 5                                   #Input: [end]
                                         #Input: [end]
                                         #Input: [end]
no                                       #Do you want to optimize the initial populations (otherwise only the rates)? [True]
                                         #Do you want to restrict all rates/initial populations to be non-negative? [True]
                                         #Do you want to continue? [True]
```
Here, you only assign columns 2-5 (out of columns 2-19) to the fit. Column 2 is the S0, which is not populated, column 3 would be the S1, column 4 the S2, as given below.

I suggest to use the following input:
```
+ S12 T1 T2 T345                         #Input: [end]
                                         #Input: [end]
+ S12 T1 k1                              #Input: [end]
+ S12 T2 k2                              #Input: [end]
+ S12 T345 k3                            #Input: [end]
                                         #Input: [end]
+ S12                                    #Input: [end]
                                         #Input: [end]
y                                        #Do you want to use bootstrap data? [False]
100                                      #How many bootstrap samples? [100]
/path/to/bootstrap_data/     #Bootstrap data directory: [bootstrap_data/] (autocomplete enabled)
                                         #Do you want to write fitting curves for all bootstrap cycles? [False]
S12 = 3 4                                #Input: [end]
T1 = 5 10 15                             #Input: [end]
T2 = 6 11 16                             #Input: [end]
T345 = 7~9 12~14 17~19                   #Input: [end]
                                         #Input: [end]
k1 = 60000.
k2 = 120000.
k3 = 800000.
                                         #Input: [end]
n                                        #Do you want to optimize the initial populations (otherwise only the rates)? [True]
                                         #Do you want to restrict all rates/initial populations to be non-negative? [True]
                                         #Do you want to continue? [True]
```

Note that here I define a kinetic species that is the sum of S1 and S2, because these two states are apparently in a fast equilibrium. If you need information on this equilibrium, then you would need to include S1 and S2 species, S1->S2 and S2->S1 reactions, and assign S1 = 3 and S2 = 4 columns.

I also merged T3, T4, and T5, because T4/5 are not strongly populated anyways, but the fit works better if all data columns are included. This is  because the fit functions will always add up to exactly 1, so the included fit data should also add to 1. I neglected the S0 here, because its population is zero throughout.

The most important part is the column assignment at the end. If you check your fit data files, the header will tell you which columns correspond to which state. In your case (3S+5T):
Column     State
2    S0
3    S1
4    S2
5    T1 (M_S=-1)
6     T2 (M_S=-1)
...
10     T1 (M_S=0)
...
15     T1 (M_S=+1)
...
19     T5 (M_S=+1)
In order to get a correct fit, you need to properly assign these columns to your species, as is done in the input above.

If you want to have an accurate estimate of the errors, you might also consider to run more than 100 bootstrap samples, if the cost is not too high for you.

Also note the initial guesses for the time constants that I have added to the input. This should ensure that the fit converges quickly, although the model should converge robustly if assignment is correct.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul Hakeem K., I repeat here my email reply to you, so that other users can also see what should be done.
> 
> Your main problem was that you did not correctly assign the columns from the population files to the kinetic species. Also, the kinetic model was not really appropriate for the data, because there is also non-zero S2 population. Therefore, the fit could not proceed correctly.
> 
> Your KEYSTROKES.make_fit file:
> 
> ```
> + S1 T3 T2 T1                            #Input: [end]
>                                          #Input: [end]
> + S1 T3 K13                              #Input: [end]
> + S1 T2 K12                              #Input: [end]
> + S1 T1 K11                              #Input: [end]
>                                          #Input: [end]
> + S1                                     #Input: [end]
>                                          #Input: [end]
> yes                                      #Do you want to use bootstrap data? [False]
>                                          #How many bootstrap samples? [100]
> /path/to/bootstrap_data/ #Bootstrap data directory: [bootstrap_data/] (autocomplete enabled)
>                                          #Do you want to write fitting curves for all bootstrap cycles? [False]
> S1 = 2                                   #Input: [end]
> T3 = 3                                   #Input: [end]
> T2 = 4                                   #Input: [end]
> T1 = 5                                   #Input: [end]
>                                          #Input: [end]
>                                          #Input: [end]
> no                                       #Do you want to optimize the initial populations (otherwise only the rates)? [True]
>                                          #Do you want to restrict all rates/initial populations to be non-negative? [True]
>                                          #Do you want to continue? [True]
> ```
> 
> Here, you only assign columns 2-5 (out of columns 2-19) to the fit. Column 2 is the S0, which is not populated, column 3 would be the S1, column 4 the S2, as given below.
> 
> I suggest to use the following input:
> 
> ```
> + S12 T1 T2 T345                         #Input: [end]
>                                          #Input: [end]
> + S12 T1 k1                              #Input: [end]
> + S12 T2 k2                              #Input: [end]
> + S12 T345 k3                            #Input: [end]
>                                          #Input: [end]
> + S12                                    #Input: [end]
>                                          #Input: [end]
> y                                        #Do you want to use bootstrap data? [False]
> 100                                      #How many bootstrap samples? [100]
> /path/to/bootstrap_data/     #Bootstrap data directory: [bootstrap_data/] (autocomplete enabled)
>                                          #Do you want to write fitting curves for all bootstrap cycles? [False]
> S12 = 3 4                                #Input: [end]
> T1 = 5 10 15                             #Input: [end]
> T2 = 6 11 16                             #Input: [end]
> T345 = 7~9 12~14 17~19                   #Input: [end]
>                                          #Input: [end]
> k1 = 60000.
> k2 = 120000.
> k3 = 800000.
>                                          #Input: [end]
> n                                        #Do you want to optimize the initial populations (otherwise only the rates)? [True]
>                                          #Do you want to restrict all rates/initial populations to be non-negative? [True]
>                                          #Do you want to continue? [True]
> ```
> 
> Note that here I define a kinetic species that is the sum of S1 and S2, because these two states are apparently in a fast equilibrium. If you need information on this equilibrium, then you would need to include S1 and S2 species, S1->S2 and S2->S1 reactions, and assign S1 = 3 and S2 = 4 columns.
> 
> I also merged T3, T4, and T5, because T4/5 are not strongly populated anyways, but the fit works better if all data columns are included. This is because the fit functions will always add up to exactly 1, so the included fit data should also add to 1. I neglected the S0 here, because its population is zero throughout.
> 
> The most important part is the column assignment at the end. If you check your fit data files, the header will tell you which columns correspond to which state. In your case (3S+5T): Column State 2 S0 3 S1 4 S2 5 T1 (M_S=-1) 6 T2 (M_S=-1) ... 10 T1 (M_S=0) ... 15 T1 (M_S=+1) ... 19 T5 (M_S=+1) In order to get a correct fit, you need to properly assign these columns to your species, as is done in the input above.
> 
> If you want to have an accurate estimate of the errors, you might also consider to run more than 100 bootstrap samples, if the cost is not too high for you.
> 
> Also note the initial guesses for the time constants that I have added to the input. This should ensure that the fit converges quickly, although the model should converge robustly if assignment is correct.
> 
> Best, Sebastian

Ok sir, Thank you for your detailed explanation.
