### ISSUE TITLE
Regarding Calculating The ICT State Population Rate Using SHARC-LVC Model

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#141]
Dear Sir,
I hope this message finds you well.
I am currently working on a project where I am studying the excited state dynamics of a molecule. Specifically, I excite my molecule into the S2 state, and I observe that it decays and populates a long-lived species. I have confirmed the long-lived nature of this species from femtosecond Transient Absorption Spectroscopy (TAS). However, when performing nanosecond TAS, I observe a very low triplet population, leading me to suspect that this long-lived species could be an Intramolecular Charge-Transfer (ICT) state.

My question is whether it is possible to calculate the rate of population of this ICT state from the S2 state using the SHARC-LVC model. Will the SHARC-LVC method allow me to obtain the ICT population rate and generate the corresponding plot?

I came across a paper titled "Nuclear Motion Driven Ultrafast Photodissociative Charge Transfer of the PENNA Cation: An Experimental and Computational Study," where SHARC was used. This has led to some confusion, as I am not sure if the same approach applies to my case involving the SHARC-LVC model.

Any guidance or advice on this matter would be greatly appreciated.

Thank you for your time and consideration.

Best regards,
Lukhmanul Hakeem K

**Comment by maisebastian** [comment]
Dear Lukhmanul Hakeem K,
in principle, if your molecule is very stiff and harmonic oscillators can adequately describe all potential energy surfaces, then LVC might work. However, nanosecond rate constants are very sensitive to tiny changes in the PESs, so I cannot give any guarantees about the accuracy. If you have an accurate electronic structure method to parametrize, it might work.

Note that you will need to compute diabatic populations in order to track electronic wave function characters. It is not easily possible to run TheoDORE on top of LVC.

The paper that you have mentioned does not use LVC, but runs SHARC with CASSCF, and only for 200fs. This is hardly comparable to the situation that you describe for your system.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul Hakeem K, in principle, if your molecule is very stiff and harmonic oscillators can adequately describe all potential energy surfaces, then LVC might work. However, nanosecond rate constants are very sensitive to tiny changes in the PESs, so I cannot give any guarantees about the accuracy. If you have an accurate electronic structure method to parametrize, it might work.
> 
> Note that you will need to compute diabatic populations in order to track electronic wave function characters. It is not easily possible to run TheoDORE on top of LVC.
> 
> The paper that you have mentioned does not use LVC, but runs SHARC with CASSCF, and only for 200fs. This is hardly comparable to the situation that you describe for your system.
> 
> Best, Sebastian

Dear Sir,
Thank you for your reply.
Best regards,
LUKHMANUL HAKEEM K.
