### ISSUE TITLE
Inquiry Regarding SHARC-LVC Method for Rate Constants of non-radiative and radiative processes.

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#144]
Dear Sir,
I have one doubt regarding whether it is possible to find out the rate constant of non-radiative and radiative processes separately from S1 to S0. In my case, I also have intersystem crossing. I am using the SHARC-LVC method, and the LVC is parametrized by the SA-CASSCF method (note: SA-CASSCF done using OpenMolcas). My aim is to determine which channel is most favorable for decay—whether it is intersystem crossing or the non-radiative decay channel.
Please help me.
Best regards,
LUKHMANUL HAKEEM K

**Comment by maisebastian** [comment]
Dear user,
whether LVC is appropriate or not depends strongly on the molecule. It is supposed to only work for rigid molecules that do not undergo any large-scale motions, like dissociation, torsion, motion of aliphatic chains, rearrangements, etc. Obviously, also the CASSCF method for parametrization needs to be adjusted carefully to the molecule. So, with the information you provided, I cannot really estimate whether you can accurately determine the rate constants of these channels.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear user, whether LVC is appropriate or not depends strongly on the molecule. It is supposed to only work for rigid molecules that do not undergo any large-scale motions, like dissociation, torsion, motion of aliphatic chains, rearrangements, etc. Obviously, also the CASSCF method for parametrization needs to be adjusted carefully to the molecule. So, with the information you provided, I cannot really estimate whether you can accurately determine the rate constants of these channels.
> 
> Best, Sebastian

Dear Sir,
Thank you for your reply. I am working on an indole derivative and have some additional questions regarding your paper "Competing ultrafast photoinduced electron transfer and intersystem crossing of [Re(CO)3(Dmp)(His124)(Trp122)]+ in Pseudomonas aeruginosa azurin: a nonadiabatic dynamics study." In your paper, you mentioned that low-frequency modes in harmonic oscillators are prone to show very large nuclear displacements. To mitigate these problems, all normal modes should be removed with 𝜔i < 300 cm−1. My doubt is whether this is applicable in all cases.
I have another question regarding the preparation of input scripts to parameterize LVC. When using the $SHARC/setup_LVCparam.py script, there's an option: "Do you want to use analytical nonadiabatic coupling vectors for lambdas: false." I am wondering why the analytical nonadiabatic coupling vectors for lambdas are set to false. My concern is whether setting this to false may affect singlet to singlet decay (for example, S1 to S0).
In your previous response, you mentioned carefully about LVC parametrization by CASSCF. Could you please explain what things I need to take note of when doing LVC parametrization by CASSCF?
Thank you for your guidance. Please help me.

Best regards,
LUKHMANUL HAKEEM K

**Comment by maisebastian** [comment]
Dear user,
since the paper you mentioned, we have gathered some more experience on how to correctly build LVC models. Important rules during parametrization are: use tighter convergence thresholds and better precision (larger integration grids in DFT, larger aux basis sets, etc). For low-frequency modes, use larger displacements. We have found that the old default in setup_LVCparam.py of 0.05 is good for modes with frequencies >700cm-1. For modes with 100cm-1<freq<700cm-1, use displacements of 0.10, for modes <100cm-1, use 0.15.
Using improved numerical precision via tighter convergence, larger grids, larger aux basis and using larger displacements all help to make the computation of the LVC parameters (lambdas and kappas) more numerically robust, so that erroneous parameters are much less likely to occur. Hence, the problems as found in the mentioned paper should be much less, and it might not be necessary to delete modes. 

About the lambdas: Note that if you select analytical NACs=False, that does not mean that no NACs are computed. Rather, they are computed numerically from wave function overlaps. This typically produces nearly identical results, but is computationally more expensive because one has to compute the 6N displacement calculations. However, these displacements can be better parallelized than one big calculation with all analytical NACSs.

About CASSCF: Well, ideally you should have already explored the PESs of the molecule with several levels of theory. You should know all electronic states that play a role in the dynamics, and then build your active space such that all these states can be consistently described. Here, it is also important to chose the number of states in SA such that the active space is stable at all relevant geometries. Finally, note that CASSCF is not very accurate for heterocycles. For pi-system-only active spaces, bright pipi* states are usually 1-2eV too high in energy. If affordable, XMS-CASPT2 should then be used instead.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear user, since the paper you mentioned, we have gathered some more experience on how to correctly build LVC models. Important rules during parametrization are: use tighter convergence thresholds and better precision (larger integration grids in DFT, larger aux basis sets, etc). For low-frequency modes, use larger displacements. We have found that the old default in setup_LVCparam.py of 0.05 is good for modes with frequencies >700cm-1. For modes with 100cm-1<freq<700cm-1, use displacements of 0.10, for modes <100cm-1, use 0.15. Using improved numerical precision via tighter convergence, larger grids, larger aux basis and using larger displacements all help to make the computation of the LVC parameters (lambdas and kappas) more numerically robust, so that erroneous parameters are much less likely to occur. Hence, the problems as found in the mentioned paper should be much less, and it might not be necessary to delete modes.
> 
> About the lambdas: Note that if you select analytical NACs=False, that does not mean that no NACs are computed. Rather, they are computed numerically from wave function overlaps. This typically produces nearly identical results, but is computationally more expensive because one has to compute the 6N displacement calculations. However, these displacements can be better parallelized than one big calculation with all analytical NACSs.
> 
> About CASSCF: Well, ideally you should have already explored the PESs of the molecule with several levels of theory. You should know all electronic states that play a role in the dynamics, and then build your active space such that all these states can be consistently described. Here, it is also important to chose the number of states in SA such that the active space is stable at all relevant geometries. Finally, note that CASSCF is not very accurate for heterocycles. For pi-system-only active spaces, bright pipi* states are usually 1-2eV too high in energy. If affordable, XMS-CASPT2 should then be used instead.
> 
> Best, Sebastian

Dear Sir,
Thank you for your reply.

Best regards,
LUKHMANUL HAKEEM K
