### ISSUE TITLE
Bug Report: Issues MC-PDFT and CMS-PDFT calculations with OpenMolcas 24.06

### ISSUE THREAD

**Issue by iamDongHwan** [sharc-md/sharc#151]
Dear Developers,

I hope this message finds you well.

I would like to bring to your attention a couple of bugs I encountered while running simulations using the MC-PDFT and CMS-PDFT methods with OpenMolcas 24.06 and the SHARC interface.

The first issue occurs in lines 3338-3340 of the SHARC_MOLCAS.py file. I found that line 3340 needs to be commented out. 

3338         if QMin['method'] in [3,4,5]:
3339             copyfiles.append(('MOLCAS.NqGrid','MOLCAS.NqGrid'))
3340 #            copyfiles.append(('GRIDFILE','GRIDFILE'))

The second issue arises in lines 982-989. Here, the indices for stateindex and enindex appear to be incorrect. Changing stateindex to 6 and enindex to 7 allowed the simulations to run correctly.

 982     elif method == 3:
 983         modulestring = '&MCPDFT'
 984         spinstring = 'Spin quantum number'
 985         energystring = 'Total MC-PDFT energy for state'
 986 #        stateindex = 5
 987         stateindex = 6
 988 #        enindex = 6
 989         enindex = 7

After making these changes, everything worked smoothly, and I was able to proceed with my simulations without any further issues. These problems may be specific to the recent version of OpenMolcas (24.06), but I wanted to share these findings in case they are useful.

Thank you for your time and for maintaining such an excellent software package.

Best regards,
Donghwan Im

**Comment by maisebastian** [comment]
Dear Donghwan Im,
thank you for your input. Could you provide a brief explanation for your proposed changes?
1) What is the harm in copying the GRIDFILE? Even in 24.06, I see that this file is created, although it might not be needed. But did you experience problems because this file was copied?
2) At least for 24.02, the change in the indices for method==3 (MC-PDFT) does not work. I saw that for XMS- and CMS-PDFT the line reads "Total MC-PDFT energy for intermediate state", but for XMS and CMS, the energies are not read for the intermediate states. For MC-PDFT, the line does not contain "intermediate" and the current labels should be correct. It might be that this is something specific to v24.06, but I am still waiting for the compile to verify.

Best,
Sebastian

**Comment by iamDongHwan** [comment]
Hello Sebastian,
Thank you for your reply!

I encountered the following error while running the dynamics simulation:

FileNotFoundError: [Errno 2] No such file or directory: '/proj/internal_group/card/dhim/TEST_DIR/SHARC_TEST/MOLCAS_CMS-PDFT/QM/scratch/master/GRIDFILE'

It appears the GRIDFILE was not generated during my calculation, and I’m still investigating the cause. 
For now, I’ve commented it out, as it’s not mandatory for the simulations.


Regarding your second comment, that was my mistake. I’ve verified that everything works correctly with version 24.06.
As for CMS- and XMS-PDFT, they seem to be reading the following lines correctly:

::    CMS-PDFT Root    1   Total energy:      -95.70708163
::    CMS-PDFT Root    2   Total energy:      -95.47808841

Best,
Donghwan

**Comment by maisebastian** [comment]
OK, now I have the 24.06 version to verify. Indeed, until 24.02 there was the GRIDFILE and now it is gone. I added a line to copy the file only if the version is lower than 24.06.

For the MC-PDFT energies, you were actually right. In 24.06, they added a "::" at the begin of the "Total MC-PDFT energy for state" line. So I added a line to increment the indices if the version is 24.06 or later.

You can find the changes in the main branch here in Github.

**Comment by iamDongHwan** [comment]
Thanks for your help =)
