### ISSUE TITLE
Inquiry About Emission Spectrum Generation Using SHARC Method

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#154]
Dear Sir,
I hope this email finds you well.
I have recently come across several SHARC-related papers, but I couldn't find any mention of generating emission spectra using the SHARC method. I was wondering why this might be challenging. Do you think this might be possible in the future, or could it be achieved by creating a new Python script? I noticed that the NeMo package in Q-Chem can generate emission spectra.

Best regards,
LUKHMANUL HAKEEM K

**Comment by maisebastian** [comment]
Dear user,
SHARC does not have a dedicated module or advanced methodology for generating emission spectra. However, simple emission spectra can be generated, and are arguably the simplest time-dependent spectra to calculate (because only oscillator strengths between ground state and active state are needed). The approach is essentially the same as described in the SHARC tutorial in section 2.9.10, but you only consider the energies and oscillator strengths from the active state to the lowest state, rather than to all states as described in the tutorial for a transient absorption spectrum.
We use and mention this approach in some of our SHARC papers, for example in https://dx.doi.org/10.1039/C9SC03671G, https://dx.doi.org/10.1021/acs.jpca.3c05841, or https://pubs.acs.org/doi/10.1021/acs.jpca.3c02899 (they might be called fluorescence or luminescence spectra rather than emission spectra in the papers).

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear user, SHARC does not have a dedicated module or advanced methodology for generating emission spectra. However, simple emission spectra can be generated, and are arguably the simplest time-dependent spectra to calculate (because only oscillator strengths between ground state and active state are needed). The approach is essentially the same as described in the SHARC tutorial in section 2.9.10, but you only consider the energies and oscillator strengths from the active state to the lowest state, rather than to all states as described in the tutorial for a transient absorption spectrum. We use and mention this approach in some of our SHARC papers, for example in https://dx.doi.org/10.1039/C9SC03671G, https://dx.doi.org/10.1021/acs.jpca.3c05841, or https://pubs.acs.org/doi/10.1021/acs.jpca.3c02899 (they might be called fluorescence or luminescence spectra rather than emission spectra in the papers).
> 
> Best, Sebastian

Dear Sir,

Thank you for your reply.

Best regards,
LUKHMANUL HAKEEM K
