### ISSUE TITLE
WFOVERLAP: Issue with reading mixed AO overlap from doublemol calculation in OpenMolcas

### ISSUE THREAD

**Issue by SoubhikM** [sharc-md/sharc#158]
Hi developers,

I am trying to calculate wf-overlap with WFOVERLAP tool between two geometries

>> Old geometry
X1 	-0.234715 	-0.379309 	0.000005
C2  -0.030530   -0.819555   0.000019
H3   0.163749   -1.866071  -0.000015
O4   0.876858    0.109668   0.000007
O5  -1.445538   -0.496496  -0.000006
H6  -1.489237    0.448818   0.000003

and another geometry which is a bit far from the earlier one

>> New geometry
X1  -0.963703 	-1.220761 	0.000074
C2  -0.525693   -1.601532   0.000156
H3  -0.265065   -2.625149  -0.000117
O4  -0.212832   -0.304631   0.000065
O5  -1.997950   -1.782841   0.000032
H6  -2.380268   -0.901653   0.000092

Unfortunately if I use the `ONEINT` generated by `doublemol` calculation, I get zero overlap between CASSCF states
<img width="1579" alt="image" src="https://github.com/user-attachments/assets/0791803b-312a-453c-9cc8-cef4f49af019">

However, if I set `ao_read=-1` and enable `same_aos` to simplify the AO evaluation and the calculation itself, I get reasonable results, which is what I expected:
<img width="1579" alt="image" src="https://github.com/user-attachments/assets/cf6b9d57-1439-412e-afb7-94867e411df2">

This leads me to suspect that my `doublemol` setup or the reading of the `ONEINT` file may be incorrect.

Any insights or suggestions would be greatly appreciated!

Files: [https://drive.google.com/file/d/1XSXcsUgQj2ozFaQFwW8xDg5JYpDvhMsL/view?usp=sharing](url)

-Soubhik

**Comment by maisebastian** [comment]
Dear Soubhik,
your initial and final geometries are really very different. So in your doublemol calculation, you will obtain very small overlaps between the basis functions from Old and New. The total overlap is somewhat proportional to the product of all the basis function overlaps. This means that, in the end, if you move your molecule, then your overlaps will be zero - because your electrons are not at the same position as they were before.

The question is now what you are actually trying to achieve. It appears that you might want to simply compare the wave functions from the two geometries. In this case, I recommend that you align the New gometry with the Old geometry (e.g., using VMD) and use the aligned New geometry. In this way, your geometries are as similar as possible, which should fix the problem with vanishing basis function overlaps.

Note that your approach is somewhat dangerous. With `same_aos`, you assume that the old and new geometries are identical, up to translation. However, your geometries are not identical, they seem to be rotated differently and they also seem to have different bond lengths. In this case, assuming `same_aos` will make the basis function overlap inconsistent with the MO coefficients of one of the calculations, so the wave function overlaps that you obtain are actually not correct. You can imagine this in a simple example with a set of p orbitals on a C atom. In geometry 1, let's say the pz orbital contributes to the pi orbital, but when you rotate it, the py orbital contributes to the pi orbital. If you now assume that both calculations have the same AOs, then the pi orbitals would not overlap correctly.

If the align-and-recompute suggestion does not work for you, then I suggest that you should compute a fine set of interpolated geometries between the two geometries and compute overlaps for all interpolation steps, and then the total overlap as product of the individual steps.

Best,
Sebastian

**Comment by SoubhikM** [comment]
Hi Sebastian,

Thanks for the quick reply. I hoped that it is indeed the drastic change of geometry that is causing zero AO overlap nor some setup or file reading problem of WFOVERLAP tool. Since I'm performing these calculations on the fly, using external software for manual rotation isn't an option. However, based on your suggestion, I applied the Kabsch algorithm to minimize the RMSD between the two sets of points, aligning the new geometry translationally and rotationally, and it seems to work very well!

Thanks a lot for your help, really appreciate it!

-Soubhik
