### ISSUE TITLE
Assistance Needed for SHARC/LVC Simulation Error During DSPLn and DSPLp Calculations

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#159]
Dear Sir,
I am currently conducting SHARC/LVC simulations for a perylenediimide derivative and have encountered an error during the LVC parameterization steps. The DSPL_000_eq directory completed successfully. However, while running the DSPLn and DSPLp directories, I encountered an error after a day of calculation. Below is the error output:
"
>>>>>>>>>>>>> Starting the WFOVERLAP job execution
START: /home/mhgrou...a/DSPL_RESULTS/DSPL_088_p/WFOVL_1_1 2024-10-25 18:08:42.972546 "/home/mhgrou.../wfoverlap.x -m 200000 -f wfovl.inp"
FINISH: /home/mhgrou...a/DSPL_RESULTS/DSPL_088_p/WFOVL_1_1 2024-10-26 23:08:58.454264 Runtime: 1 day, 5:00:15.481718 Error Code: -9
START: /home/mhgrou...a/DSPL_RESULTS/DSPL_088_p/WFOVL_3_1 2024-10-26 23:09:01.215717 "/home/mhgrou.../wfoverlap.x -m 200000 -f wfovl.inp"
FINISH: /home/mhgrou...a/DSPL_RESULTS/DSPL_088_p/WFOVL_3_1 2024-10-26 23:10:03.165259 Runtime: 0:01:01.949542 Error Code: 0

Error Codes:
WFOVL_1_1  -9  WFOVL_3_1  0
Some subprocesses did not finish successfully!
"
The calculation did not complete successfully, and I could not identify any error in the qm.err file or in wfovl.err. Additionally, when I checked the scratch directory, the ORCA calculations appeared to have completed without any issues.

Could you please assist me in resolving this issue or provide guidance on possible steps to troubleshoot it?

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear lukhman9020,
it appears that something went wrong with the overlap calculation of the singlet states. A computation time of 1 day and 5h for wfoverlap indicates that you have an extremely large overlap calculation. What is your wfthres? How many determinants are in the det.1 files in the SAVEDIR? Could you slightly reduce the wfthres? Even going from 1.0 to 0.999999 reduces the number of determinants dramatically, and then going to 0.99999 or lower reduces even more. 

I am asking because, without further information, I do not know exactly what is the reason for the crash. It could be due to excessive memory usage of wfoverlap, which triggered the OS to kill the process. What does the WFOVL_1_1/wfovl.out file say? Can you post it maybe?

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear lukhman9020, it appears that something went wrong with the overlap calculation of the singlet states. A computation time of 1 day and 5h for wfoverlap indicates that you have an extremely large overlap calculation. What is your wfthres? How many determinants are in the det.1 files in the SAVEDIR? Could you slightly reduce the wfthres? Even going from 1.0 to 0.999999 reduces the number of determinants dramatically, and then going to 0.99999 or lower reduces even more.
> 
> I am asking because, without further information, I do not know exactly what is the reason for the crash. It could be due to excessive memory usage of wfoverlap, which triggered the OS to kill the process. What does the WFOVL_1_1/wfovl.out file say? Can you post it maybe?
> 
> Best, Sebastian

Dear Sir,

Thank you for your previous reply. I realized that I had set the wfthres value to 0.9997, assuming you were asking about the value specified in setup_LVCparam.py (state threshold for selecting determinants to include in overlaps. For hybrids, or when not using TDA, I noticed the eigenvector  X might have a norm larger than 1, which made me consider adjusting this threshold to 0.9997)

While reviewing the det.1 file, I encountered some difficulty understanding its content. To help clarify, I have shared the det.1, det.3, and other relevant files from the SAVEDIR directory, along with wfovl.out files from WFOVL_1_1 and WFOVL_3_1 in a Google Drive link  https://drive.google.com/drive/folders/1KAjtNHcXIFQoDJZ34OcqhsOTYIt6_QVA?usp=sharing

As an undergraduate in my final year, I am currently part of a physical chemistry lab primarily focused on ultrafast spectroscopic techniques, and I am the only one in my group working with SHARC 3.0. I am eager to deepen my theoretical understanding of SHARC, especially regarding wavefunction overlaps and the det.1 files. I have read the SHARC manual and the review article "Nonadiabatic Dynamics: The SHARC Approach"; however, I still find myself struggling with certain aspects, likely due to my beginner background.

If you could recommend any additional resources or articles that elaborate on wavefunction overlap and other relevant topics in SHARC, it would greatly enhance my comprehension and help me build a strong theoretical foundation in this area.

Thank you very much for your time and assistance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear Lukhmanul,
it looks like your triplet overlap calculation worked perfectly fine, but the singlet calculation did not. This is most probably because the singlet calculation is extremely large, with about 35000 blocks per side/spin. These calculations should in principle be possible, but will require tens of GB of RAM. Make sure that you provide enough memory in ORCA.resources and that the machine also has that much memory available for the job. Alternatively, while for LVC construction a very tight wfthres is really important (we are currently preparing a manuscript on that topic), if you cannot otherwise finish your computation, then you should probably reduce the wfthres a bit. You can first try 0.9995, then 0.999, and that should probably be enough.

If you are interested, I can recommend you this paper: https://dx.doi.org/10.1021/acs.jctc.5b01148, which is the original publication where we describe the algorithm behind wfoverlap.x. It discusses the different quantities that are needed (the AO overlaps, the MO coefficients, and the determinants+coefficients), it describes how the overlaps are computed in steps, and it describes how the wave functions are truncated (i.e., what wfthres does). 

An interesting follow-up work is https://pubs.acs.org/doi/10.1021/acs.jctc.9b00235. It goes a bit deeper into the discussion of how large the errors in the overlaps are depending on wfthres, although in my opinion, their estimates for the errors correspond to a worst-case scenario. Note that the more efficient algorithms described in this second paper are not currently available in SHARC. This is because their algorithms are specifically tailored to CIS/TDA-style wave functions, whereas wfoverlaps.x can deal with any linear combination of Slater determinants (e.g., also from CASSCF, MRCI).


Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, it looks like your triplet overlap calculation worked perfectly fine, but the singlet calculation did not. This is most probably because the singlet calculation is extremely large, with about 35000 blocks per side/spin. These calculations should in principle be possible, but will require tens of GB of RAM. Make sure that you provide enough memory in ORCA.resources and that the machine also has that much memory available for the job. Alternatively, while for LVC construction a very tight wfthres is really important (we are currently preparing a manuscript on that topic), if you cannot otherwise finish your computation, then you should probably reduce the wfthres a bit. You can first try 0.9995, then 0.999, and that should probably be enough.
> 
> If you are interested, I can recommend you this paper: https://dx.doi.org/10.1021/acs.jctc.5b01148, which is the original publication where we describe the algorithm behind wfoverlap.x. It discusses the different quantities that are needed (the AO overlaps, the MO coefficients, and the determinants+coefficients), it describes how the overlaps are computed in steps, and it describes how the wave functions are truncated (i.e., what wfthres does).
> 
> An interesting follow-up work is https://pubs.acs.org/doi/10.1021/acs.jctc.9b00235. It goes a bit deeper into the discussion of how large the errors in the overlaps are depending on wfthres, although in my opinion, their estimates for the errors correspond to a worst-case scenario. Note that the more efficient algorithms described in this second paper are not currently available in SHARC. This is because their algorithms are specifically tailored to CIS/TDA-style wave functions, whereas wfoverlaps.x can deal with any linear combination of Slater determinants (e.g., also from CASSCF, MRCI).
> 
> Best, Sebastian

Dear Sir,
Thank you very much for your reply.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, it looks like your triplet overlap calculation worked perfectly fine, but the singlet calculation did not. This is most probably because the singlet calculation is extremely large, with about 35000 blocks per side/spin. These calculations should in principle be possible, but will require tens of GB of RAM. Make sure that you provide enough memory in ORCA.resources and that the machine also has that much memory available for the job. Alternatively, while for LVC construction a very tight wfthres is really important (we are currently preparing a manuscript on that topic), if you cannot otherwise finish your computation, then you should probably reduce the wfthres a bit. You can first try 0.9995, then 0.999, and that should probably be enough.
> 
> If you are interested, I can recommend you this paper: https://dx.doi.org/10.1021/acs.jctc.5b01148, which is the original publication where we describe the algorithm behind wfoverlap.x. It discusses the different quantities that are needed (the AO overlaps, the MO coefficients, and the determinants+coefficients), it describes how the overlaps are computed in steps, and it describes how the wave functions are truncated (i.e., what wfthres does).
> 
> An interesting follow-up work is https://pubs.acs.org/doi/10.1021/acs.jctc.9b00235. It goes a bit deeper into the discussion of how large the errors in the overlaps are depending on wfthres, although in my opinion, their estimates for the errors correspond to a worst-case scenario. Note that the more efficient algorithms described in this second paper are not currently available in SHARC. This is because their algorithms are specifically tailored to CIS/TDA-style wave functions, whereas wfoverlaps.x can deal with any linear combination of Slater determinants (e.g., also from CASSCF, MRCI).
> 
> Best, Sebastian

Dear Sir,
Thank you for your support, I want to inform you that, now the calculation is working.

Best regards,
LUKHMANUL HAKEEM K
