### ISSUE TITLE
QM/MM TSH - Absolute Energy is decreasing fast

### ISSUE THREAD

**Issue by jokurian** [sharc-md/sharc#17]
Hi,
I am doing QM/MM surface hopping on molecule with explicit water in MM. The initial conditions were generated by using MD (using GROMACS). In all the trajectories, in like 10fs, the absolute energies (Energies in diagonal basis) of the states are decreasing by 50eV (But the energy difference between the excited states are ok). 
So what could be the reason of the extreme stabilization of the system? Is it an artifact of using the MM water?

Other details : Started the dynamics from S6. Water model is TIP3P. Check the image for the energy plot.
![pes](https://user-images.githubusercontent.com/68368567/109668474-3b4b4980-7b97-11eb-87f7-75eac910dc03.png)

Thanks,
Jo

**Comment by maisebastian** [comment]
Dear Jo,
I have seen similar problems in the past. In my case, this was mostly due to the fact that I accidentally prepared the initial conditions using SHAKE (which should be used in combination with TIP3P) but then did not use any constraints in SHARC (which just now became available). Hence, the water molecules with frozen bond lengths suddenly become unfrozen in the excited-state dynamics, which leads to a large change in the potential energy. 
There are two ways to solve this problem:
- Make new initial conditions with a flexible water model like SPC/FW. Do not forget to update the force field file given to SHARC in Tinker format.
- Download the sources for SHARC 2.1.1 (from today) that include the RATTLE algorithm. Use the RATTLE algorithm to freeze all OH and HH bond lengths for all water molecules.

Best regards,
Sebastian
