### ISSUE TITLE
wfoverlap installation/testing

### ISSUE THREAD

**Issue by felixplasser** [sharc-md/sharc#21]
There are some improvements in wfoverlap

- Interface to OpenMolcas without also using Columbus [fa7ef5f]
- Streamline of testing routines [f7bd07d3e]
- Streamline of Makefile [53cf6969cd3]

Should we include these into the main SHARC distribution? I don't think it is possible to do this via a Merge Request but we can copy the files manually.

**Comment by maisebastian** [comment]
Dear Felix,
thanks for letting me know. Did you push these changes to the wfoverlap repository? Otherwise I will send you an email to ask for the new files. I agree that we currently cannot directly merge the standalone wfoverlap package into the SHARC package, but with the files we can include it manually.

Best regards,
Sebastian
