### ISSUE TITLE
Out of Date SHARC 2.1 Tutorial

### ISSUE THREAD

**Issue by pcalio** [sharc-md/sharc#22]
Hello, 

I am new to SHARC-md and I am in the process of learning about the various features of SHARC by following the tutorial for SHARC 2.1 with OpenMolcas (version 18.09 and 21.02). I have verified both my SHARC compilation and OpenMolcas versions, but I am noticing large differences between my absorption spectra and the absorption spectra in Fig 2.1. I understand that discrepancies can arise due to different compilers and OpenMolcas versions, but I have seen negligible effects on different OpenMolcas versions on the absorption spectrum that make me wonder if certain SHARC scripts are causing the discrepancies. For example, I have noticed different interactive prompts from molcas_input.py (different coordinates for nitrogen then those presented in the tutorial), wigner.py (different masses for N and H) and setup_init.py (different run script setup prompts) even though they are from SHARC 2.1. This makes me wonder how these scripts (and possibly others, such as excite.py) affect the absorption spectra in Fig 2.1, and I wonder if its possible to update the tutorial using updated SHARC scripts?

**Comment by maisebastian** [comment]
Dear User,
thanks for bringing these typos in the tutorial to our attention. We will fix them with the next release of SHARC.

Here some remarks to the differences that you found:
- molcas_input.py: The initial coordinate of the nitrogen atom is indeed not the same as printed in the tutorial. But keep in mind that these are just the initial coordinates for an optimization. The end result of this optimization should not depend on the initial coordinates, so the results should be fine.
- wigner.py: For me, the masses are fully consistent between tutorial and output from wigner.py version 2.1.
- setup_init.py: Yes, there is a difference in the description of the run script mode, which was probably updated at some point in the script to be easier to understand. This does not affect the output of the setup script in any way, and the tutorial will be updated at the next opportunity.

However, when I reran the tutorial today, I indeed noticed that OpenMOLCAS produces slightly different results in the frequency calculation as given in the tutorial:
Tutorial frequencies:
Frequencies (cm^-1) used in the calculation:
1 977.8746
2 1022.0225
3 1215.0055
New results:
Frequencies (cm^-1) used in the calculation:
   1     973.9402
   2    1022.0837
   3    1218.4429

I currently do not see why our current OpenMOLCAS installation produces different frequencies as it used to be. However, I am convinced that the difference in frequencies is not due to anything change in SHARC.

The different results of the frequency calculation also explains the different absorption spectrum that you obtained. Most likely, the different frequency results produced a different list of geometries in initconds, which in turn leads to different excitation energies and oscillator strengths. We will also update these figures when we update the tutorial. However, we will also add a more general remark to the tutorial that in principle we cannot guarantee that the figures in the tutorial can be reproduced. 

I am sorry for your trouble with the mentioned inconsistencies in the tutorial. However, it does not appear that you need to be worried about the differences, as they seem to be mostly due to the different results obtained with OpenMOLCAS.

Best regards,
Sebastian Mai
