### ISSUE TITLE
Dump a MOLDEN-format file with natural orbitals from the 'single-point' script?

### ISSUE THREAD

**Issue by srk** [sharc-md/sharc#23]
How to dump a MOLDEN-format file with natural orbitals from the SHARC-MD 'single-point' script (after manual selection of, say, a specific frame of a dynamics trajectory)? What modifications would be needed to , for example, the OpenMOLCAS template, to make sure this happens?

**Comment by maisebastian** [comment]
Dear user,
if you are only looking for single point calculations (like from setup_single_point.py), then probably the simplest way is to add "debug" to the MOLCAS.resource file. In this way, the scratchdir is not deleted and you can retrieve any of the generated Molden files from the scratch. 
Copying the any of the other Molden files (except the MOLCAS.rasscf.molden) from the scratchdir somewhere else would require changes in the code of SHARC_MOLCAS.py. This would require in stripWORKDIR() to add the desired Molden files to the kept files (otherwise they will be deleted once Molcas is finished) and then in saveJobIphs() to actually copy the desired Molden files to some target directory (like a subdirectory of the savedir).

Best,
Sebastian
