### ISSUE TITLE
SHARC + Gaussian 16, TDDFT fails after certain steps

### ISSUE THREAD

**Issue by jsuguy** [sharc-md/sharc#25]
I have been testing SHARC + Gaussian 16 on the methylenesilane (H2C=SiH2) that is the example SHARC provides. After the “nsteps” is changed from 3 to 2000, the TDDFT fails on timestep #481 with 0.5 fs stepsize. The initial state is S1, and there is no 'Surface Hop’.

I prepared 100 trajectories via wigner.py, setup_init.py, excite.py and setup_traj.py for the same molecule. Most trajectories crashed as indicated by the README file before reaching #2000, and the most calculations stopped around timestep #100.

I replaced grad_select by grad_all, and/or changed the arguments for keywords: hopping-procedure, coupling, surf, ekincorrect, reflect_frustrated, etc., but the calculations fail at almost the same time. Finally, I set “ekincorrect none”, the calculations stopped around #210. According to the manual, in this setup, kinetic energy is not adjusted, jumps are never frustrated. However, the calculation still cannot finish 2000 steps.

Do you have any ideas as to what could be the source of this failure with Gaussian TDDFT?

**Comment by maisebastian** [comment]
Dear Jian-Ge Zhou,
it is very likely that the molecule either undergoes decay towards the S1/S0 conical intersection or undergoes some kind of dissociation. In both cases, the energy gap between S0 and S1 would become very small (in the files you sent, the step before the crash had a gap of 0.044eV)), which typically leads to bad convergence of the ground state SCF procedure. Here the problem is that normal Kohn-Sham DFT assumes that the ground state can be well described by a single KS determinant, but if the S0-S1 gap is very small, this is a bad assumption. This is a very general problem of all single-reference methods and there is no real fix. Such problems require multi-reference methods or at least spin-flip methods (but the latter are not available in SHARC currently). As a low-accuracy work-around, you can have a look at the "force_hop_to_gs" option for SHARC. If you choose an appropriate threshold, the trajectory would hop from S1 to S0 before convergence problems occur. However, keep in mind that this typically leads to an overestimation of the S1->S0 decay rate.

Best regards,
Sebastian Mai

**Comment by jsuguy** [comment]
Dear Dr. Mai:

Thank you very much for your response! My test supported your observation. In some sense, the current Gaussian TDDFT cannot provide satisfactory results for the nonadiabatic dynamic simulation for my molecule.

Best regards,

Jian-Ge Zhou
