### ISSUE TITLE
sharctraj_to_initconds.py seems to be broken

### ISSUE THREAD

**Issue by MartinPeschel** [sharc-md/sharc#70]
Hi SHARC-Team!

I recently switched to using sharc3.0. However, in the new version, the script sharctraj_to_initconds.py seems to be broken.
I can not even get the corresponding test to run. It crashes with the following error:

`"$SHARC/sharctraj_to_initconds.py", line 786
    if inf['version'] == 1.0:
IndentationError: unexpected indent`

Indeed, the indentation is off in multiple places in the file.
I suspect something might have gone wrong when converting to python3...

Greetings, Martin

**Comment by maisebastian** [comment]
Dear Martin,
thanks for spotting this problem. Indeed, it seems that something went very wrong in this script. The script has now been fixed in https://github.com/sharc-md/sharc/blob/main/bin/sharctraj_to_initconds.py.
There is also a new option -T that allows to select random steps between two given times (not time steps, as in -S). The new option is intended to work with the adaptive time step features of the SHARC 3.0.

If there are any problems still unresolved, please feel free to write us again.

Best,
Sebastian
