### ISSUE TITLE
Problem in SHARC-ORCA QM/MM calculations

### ISSUE THREAD

**Issue by debarshibanerjee** [sharc-md/sharc#82]
Dear SHARC devs,

When running a SHARC+ORCA+TINKER QM/MM calculation, I seem to get the following error in the tinker run:

>  This is a QM/MM calculation
QMMMSETUP -- Wrong NbInQM value **
TINKER is Unable to Continue; Terminating the Current Calculation
>

I am not sure what I am doing wrong. The test for SHARC-ORCA-TINKER QM/MM (in tests.py) works for me, but I am uncertain about any mistakes I might be making.

The generated 'TINKER.key' file reads:

>parameters ~/namd/dimer-1_118326/3-TSH_S1/init/ICOND_00000/ORCA.qmmm.ff
QMMM 26880
QM -1 20
MM -21 26880
OPENMP-THREADS 16
>

Can you help me debug this issue?

**Comment by maisebastian** [comment]
Dear Debarshi,
I think the most likely origin of your problem is the QMMM.table file. But in order to help you further, I might need your input files. Can you provide me with the files (you can send them via email if you prefer)?
Best,
Sebastian

**Comment by debarshibanerjee** [comment]
Thanks a lot for your response, Sebastian.
I sent you the files via email!

Best,
Debarshi

**Comment by maisebastian** [comment]
Dear Debarshi,
I think I could identify the issue. However, I had to make some assumptions because you did not provide the files needed for a specific calculation (e.g., QM.in, ORCA.resources, ...). Hence, I set up a job from your files using amber_to_initconds.py and setup_init.py.
Here is what happened for me:
1) `$SHARC/amber_to_initconds.py -t 2. final_ac2.prmtop 1.rst7 1.rst7` works without problem (no autoimage needed here).
2) `$SHARC/setup_init.py` works, but because there is no `qmmm` keyword in `ORCA.template`, it does not ask for the file names of the table and force field file.
3) To make the calculation a QM/MM job, I added `qmmm` to ORCA.template and the path to Tinker and file names for table and ff file to ORCA.resources. I also copied the table and ff files into the folder of the created job.
=> For me, using ORCA 4.2.1, Tinker 6.3.3, and SHARC 3.0.1 the job now runs through.

What is a bit surprising is that you have a "~" symbol in the force field path in your TINKER.key file. Normally, SHARC_ORCA.py converts this path to an absolute path and replaces "~" by the corresponding path. This tells me that SHARC_ORCA.py possibly did not find the file, maybe because it was not copied to the right place. 

I recommend that you add `qmmm` to your ORCA.template and try to set up a job again.

**Comment by debarshibanerjee** [comment]
Dear Sebastian,

I sent you the wrong template file. I did have qmmm in the one I am using. Let me re-send the stuff to you. Also I am using ORCA 5.0.4 (the rest are the same versions as you).

The TINKER.key now reads:

> parameters /media/users/debarshi/phd/project-1/namd/dimer-1_118326/3-TSH_S1/init/ICOND_00091/ORCA.qmmm.ff
QMMM 26880
QM -1 20
MM -21 26880
OPENMP-THREADS 8


I still get the same error:

>QMMMSETUP -- Wrong NbInQM value **
 TINKER is Unable to Continue; Terminating the Current Calculation

**Comment by maisebastian** [comment]
Dear Debarshi,
I finally realized what is the problem in your calculation. The Tinker error message is very unclear about that, but the error appears because you have more atoms than the "maxqmmm" value in tk2qm_s allows. You will need to change the value in "qmmm.i" and recompile Tinker. If you installed it through OpenMolcas, you might be able to change the value in one of the patch files before running "molcas get_tinker" (the value appears to be 1000 by default).

**Comment by debarshibanerjee** [comment]
Thanks! This seems to work :)
