### ISSUE TITLE
No such file or directory: ...master_1/ORCA.molden.input

### ISSUE THREAD

**Issue by jakobcasa** [sharc-md/sharc#86]
Dear All

It seems as sharc does not produce a molden file which is required to continue to finalse the calculatation, meaning for every submitted job it does run a around 20 min and breakes down and it tells me

No such file or directory: ...master_1/ORCA.molden.input
How it avoid this issue 

Sorry if there is an obvious solution to this, Thank you

Best

**Comment by maisebastian** [comment]
Dear user,
unfortunately, I cannot make much from your description. It would be helpful to have some or all of:
- input files
- files in scratchdir
- files in savedir
- program versions
- relevant environment variables
Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear Sebastian

Im sorry about this.

here Is the files from the master_1 directory:
[Archive.zip](https://github.com/sharc-md/sharc/files/13277899/Archive.zip)

and the files from the save directory
[Archive 2.zip](https://github.com/sharc-md/sharc/files/13277964/Archive.2.zip)

And all the files out of the folder where the run.sh is in:
[Archive 3.zip](https://github.com/sharc-md/sharc/files/13277995/Archive.3.zip)

The Sharc version is 2.1.

If you need anything else, let me know.

Thank you for the help,
Best
JakobC

**Comment by maisebastian** [comment]
Dear Jakob,
thank you. From QM.log it looks like you did many attempts and it crashed in several different ways (sometimes after 20 min, sometimes faster). It also produced mo and det files in the savedir. Unfortunately, the archives you sent are not really consistent with your error message. The ORCA.log for example crashes right in the beginning during integral generation, which does not match with the fact that at least one calculation had worked before.

Could you please send me a consistent set of outputs? 

Additionally, have you tried the most up-to-date SHARC_ORCA.py (https://github.com/sharc-md/sharc/blob/main/bin/SHARC_ORCA.py)? There might be several bug fixes that could be relevant for you. Do not worry, the interface will be compatible with sharc.x from SHARC 2.1, if you want to stay with that version.

Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear Sebastian,

Thank you for the feedback. 

I have encountered multiple errors related to "not having loaded" the correct module. I have updated the SHARC_ORCA.py. I must first calculate the ICOND_00000 before the other traj can be launched. I will let you know as soon as possible whether the new SHARC_ORCA.py was able to solve my issue or not. If not, I will attach the same files as before.

Best
Jakob

**Comment by jakobcasa** [comment]
Enclosed, I sent you the two zip files I have already and sent you ones, now with consistent output files. 

The SCRATCH directory:
[Archive.zip](https://github.com/sharc-md/sharc/files/13282685/Archive.zip)

The SAVE folder:
[Archive 2.zip](https://github.com/sharc-md/sharc/files/13282695/Archive.2.zip)

the folder where the run.sh is
[Archive 3.zip](https://github.com/sharc-md/sharc/files/13282717/Archive.3.zip)

Note I'm doing 20 Wigner distributions, and in some, I had to kill the job once since I forgot again that I had to load a certain module.

Thank you for the help.

Best
Jakob

**Comment by maisebastian** [comment]
Thanks, these files indeed look consistent. The problem is probably that you do not use the correct openMPI module for your ORCA version. For ORCA 5.0.3, you need to use OpenMPI 4.1.1, please refer to the manual. 

But note that this appears to be a different error than the one you described before - that it runs for 20min and then gives you the error. In your latest files, ORCA crashes already after 1 second. If you want to have the other problem (after 20min checked, you would need to send those output files).

The error message is indeed the same (but the reason is different, here OpenMPI version, in the 20min runs likely something else). The problem is that ORCA does not produce non-zero exit codes on error, so the interface does not really realize the crash in the ORCA job until it tries to look at the results. And here the first attempt is to make a Molden file and copy it to the savedir. As the job crashed, the Molden file cannot be produced and then not copied, leading to the error message you see. 

Best,
Sebastian

**Comment by jakobcasa** [comment]
Solved. The reason for the crash was that the loaded module package was loading one module that seemed to interfere with the mpi of Orca. By accident, I could unload the correct module.

Thank you for the help

Best Jakob
